### PR TITLE
V1.0d

### PR DESCRIPTION
**Pull request by ausdkunst**
Deleted unused files

### CODE REVIEW

**Comment by ausdkunst** [comment]
Hi Israel, I thought http://creativecommons.org/licenses/by-nc-sa/4.0/ would allow anyone to make changes to this project, no? Please let me know which license allows people to makes changes.
Thanks, 
Ross

**Comment by FGDATA** [comment]
Hi Ausdkunst,

Affirmative. 

BY => It allows anyone to redistribute 

<u>If BY</u>, then: 
NC- Non-Commercial
SA- Share alike - any redistribution, with modifications or not, HAS to keep your original license
ND - Not Derivatives, Limits/prohibits the redistribution of versions with modifications.

So
CC-BY : allows redistribution without additional limitations. Can be re-released to GPL without additional requests
CC-BY-SA  : allows redistributions, but other sites need to respect your decision of the license in use
CC-BY-NC-SA : allows redistributions, but can't be used for commercial purposes and other sites redistributing need to respect your decision of the license in use
CC-BY-NC-SA-ND : Allows redistributions but can't be used for commercial purposes, other sites redistributing need to respect your decision of the license in use, and it forbids redistribution of versions containing modifications

That's basically how the Creative Commons family work

@IAHM-COL

**Comment by ausdkunst** [comment]
Thanks! This project is under Creative Commons BY-NC-SA 4.0 and yet I don't have write access to merge pull request.

**Comment by FGDATA** [comment]
Now you (and all FGMEMBERS-NONGPL members) have access to it
IH-COL

**Comment by ausdkunst** [comment]
Thanks! 

Ross

**Pull request merged**
